// frontend/src/components/TaskList.tsx
/**
 * タスク一覧コンポーネント
 * タスクの配列を受け取り、TaskItemコンポーネントで表示する
 */
import type { Task } from "../api/taskApi";
import { TaskItem } from "./TaskItem";

interface TaskListProps {
  tasks: Task[];
  onToggle: (id: number, completed: boolean) => void;
  onDelete: (id: number) => void;
  processingIds: Set<number>;
}

export function TaskList({
  tasks,
  onToggle,
  onDelete,
  processingIds,
}: TaskListProps) {
  if (tasks.length === 0) {
    return (
      <div className="text-center py-8 text-gray-500" role="status">
        タスクがありません
      </div>
    );
  }

  return (
    <ul className="space-y-3" role="list" aria-label="タスク一覧">
      {tasks.map((task) => (
        <TaskItem
          key={task.id}
          task={task}
          onToggle={onToggle}
          onDelete={onDelete}
          isProcessing={processingIds.has(task.id)}
        />
      ))}
    </ul>
  );
}

// frontend/components/TaskList.vue
<script setup lang="ts">
import type { Task } from '~/types/task'

defineProps<{
  tasks: Task[]
  processingIds: Set<number>
}>()

const emit = defineEmits<{
  toggle: [id: number, completed: boolean]
  delete: [id: number]
}>()
</script>

<template>
  <div v-if="tasks.length === 0" class="text-center py-8 text-gray-500" role="status">
    タスクがありません
  </div>

  <ul v-else class="space-y-3" role="list" aria-label="タスク一覧">
    <TaskItem
      v-for="task in tasks"
      :key="task.id"
      :task="task"
      :is-processing="processingIds.has(task.id)"
      @toggle="(id, completed) => emit('toggle', id, completed)"
      @delete="(id) => emit('delete', id)"
    />
  </ul>
</template>
